### ISSUE TITLE
[HUD] Fix current item draw

### ISSUE THREAD

**Issue by scawful** [scawful/Oracle-of-Secrets#12]
Outdated: Currently there are some errors with the proper icon being drawn in the HUD for the Wolf Mask and Bunny Hood that need to be investigated based on their current SRM values. 

Update: Current item draw graphics have been fixed as apart of #50 however there are still issues with the item icon updating when an item is pulled from a chest or given by a sprite.

**Comment by JaredBrian** [comment]
oh i didn't notice those while testing, that is something I was looking for while doing my fixes so I'll check again.

**Comment by scawful** [comment]
The description here is outdated. I think it would be more accurate to say this issue encompasses the item icon updating after pulling from a chest, which currently still does not assign the item you received but rather blanks out the HUD item box. I believe you fixed all the alignment issues with the graphics/items mappings themselves.
