### ISSUE TITLE
Patch 0.102 bugs

### ISSUE THREAD

**Issue by fortwoone** [scawful/Oracle-of-Secrets#18]
Here is a list of all the bugs I found in v. 0.102 of the game:

- Roc's Feather doesn't prioritise Link over the things he jumps on, so he is drawn BEHIND them.

- The spiky rollers in Tail Palace deal 3 hearts per hit, rendering them extremely dangerous for a regular player (i.e. they can twoshot Link as he can only come in once he has 4 hearts, see screenshot 1)

![Legend of Zelda, The - Oracle of Secrets (SNES)_001](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/1e35bb06-3878-4cdc-8e71-e99ec87b17ca)

- Opening the Big Key chest in Tail Palace assigns the Y button to the Zora Mask (even though you can't transform until actually getting the mask), see video 1 : https://github.com/scawful/Oracle-of-Secrets/assets/74463377/84bc573d-45cd-4116-b8d5-730e905c40b0

- The aforementioned bug also happens when you open the chest containing the King's Sword in Kalyxo Castle, another chest on 3F containing a key and guarded by a white flail knight in Kalyxo Castle as well, and a 20-Rupee chest in the Zora Sanctuary.

- A similar bug happens when you open the Big Key chest in the Zora Sanctuary. Instead of the Zora Mask, the Magic Mirror is assigned to Y upon obtaining the item. If you try using the Mirror without opening the menu, the game will act as if you selected the Lamp instead.

- This cave in Wayward Village causes the music to change to the Toadstool Woods' theme once you go in and leave (screenshot 2)
 ![Legend of Zelda, The - Oracle of Secrets (SNES)_002](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/6a778e6b-1bf4-43a6-bc44-8d54319f6e78)

- Kalyxo Castle's door graphics become corrupt during the intermediate "open" frame (screenshot 3) 

![Legend of Zelda, The - Oracle of Secrets (SNES)_003](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/a5583904-59eb-4e3d-ba5b-7d2bb134bf95)

- Upon coming into Kalyxo Castle from the garden portion requiring to go through the dungeon, all sprites despawn and the floor order becomes incorrect (e.g. B2 is marked as 1F and B3 becomes B1). Several graphics (such as the jail cell bars and jail table tiles, as well as the bone graphics) get corrupted until you come back into the actual dungeon. Everything returns to normal if you leave through one of the main entrances of the dungeon, which isn't possible unless you use a walk-through-walls cheat. (see screenshots 4 and 5 for corrupted graphics and the softlock cause respectively).

![Legend of Zelda, The - Oracle of Secrets (SNES)_004](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/b224f803-22bb-4d47-ad4d-dc0674e872dd)
![Legend of Zelda, The - Oracle of Secrets (SNES)_005](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/7c3c4dd9-7ecb-4406-af43-0ffde80836e3)

- Floor order sometimes also becomes incorrect if you try going upstairs from 1F, and the game will mark the upstairs floor as 1F and consider the actual 1F to be B1, All floor positions are kept so until you leave the dungeon.

- If you bought an Empty Bottle and assign it to the Y Button, the Book of Secrets appears in your inventory even though you can't use it nor select it, see video 2 : https://github.com/scawful/Oracle-of-Secrets/assets/74463377/d3e4ddd7-56eb-467c-abab-e26ee238019d

- A remnant of the lamp light graphic (the little area allowing you to see your way through dark caves) appears in Zora Sanctuary in the 3rd video's circumstances: https://github.com/scawful/Oracle-of-Secrets/assets/74463377/19c049de-f799-4f99-bc29-ca9044f799dc

- Upon diving with the Zora Mask, you are slowed down. This speed restriction is lifted with a sword slash. If you remove the mask or return to Link's human form manually while underwater, you will stay underwater and will end up with a wrong layering. Everything, bar the layering, returns to normal once you leave water (see video 4) : https://github.com/scawful/Oracle-of-Secrets/assets/74463377/61a19a38-ecdd-4fae-96c4-edd3791ef2ec

- If you messed up with said layering and attempt to go downstairs afterwards, Link will be stuck in his swimming state with nowhere to go towards. This effectively softlocks the player.

- With a precise button combo, you can initiate a slash and jump in place right afterwards (video 5) : https://github.com/scawful/Oracle-of-Secrets/assets/74463377/d4eb6e7a-f90d-4ab0-8bb1-82333f1354ea

- You get set back to the swimming state upon pressing a button underwater. Anything you carry despawns as well (video 6) : https://github.com/scawful/Oracle-of-Secrets/assets/74463377/17881521-c706-4b58-b713-4989813f2689

- Stalfos are unaffected by water and can walk on it (likely because they weren't programmed to have any interaction with water).

- Item drops from enemies don't sink in deep water and don't interact with it at all (screenshot 6). Link cannot interact with them in his swimming state, but if he transforms into a Zora and dives underwater, he can still pick the items up.

![Legend of Zelda, The - Oracle of Secrets (SNES)_006](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/d64d0a84-75d0-4056-b9ea-8668c4beebfd)

- Zora Link doesn't properly interact with the hole in B3. Once you get in swimming state, you can return to normal by pressing Y. It won't work if you try it above the hole. This lasts even if you return to human Link using the mask again, you need to select another item after pressing Y. If you return to human Link with the R Button, you get softlocked in swimming state and break the dungeon camera. Everything returns to normal if you select another item in the menu as Zora Link, but if you attempt falling in the hole as human Link, the game will act as if you landed in water afterwards and may end up softlocked anyway. To avoid any potential softlocks, stay as Zora Link, go in the water, dive, resurface and leave using the warp after having returned to Human Link. (video 7) https://github.com/scawful/Oracle-of-Secrets/assets/74463377/427d0e02-7585-4a65-b090-011f91a14083

- The slab here is unreadable due to the text scrolling before giving the player any chance to read it (screenshot 8).
![Legend of Zelda, The - Oracle of Secrets (SNES)_007](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/5b27984c-7e9d-4ebe-84ab-d2926462a390)

- The shooters positioned on the outermost holes on the upper wall (see previous screenshot) cannot reach Zora Link while he is underwater, due to the balls stopping when hitting certain wall tiles. Since they only trigger when Zora Link is underwater, this means they can't reach Link at all.

- The key in the room affected by the softlock described with video 7 does not spawn. As a result, there are only three keys whereas the dungeon needs four keys in order to progress further. This means Zora Temple is not legitimately completable in this build.

- Fireballs are not stopped by key blocks.

- Green Jumping Pokeys go through walls.

- Enemies in the room shown in screenshot 9 have incorrect spawn positions and no collisions, i.e. they go through walls as well.
![Legend of Zelda, The - Oracle of Secrets (SNES)_008](https://github.com/scawful/Oracle-of-Secrets/assets/74463377/7c896cf5-c086-4596-97ee-ca1b27ebf70d)

- If Zora Link dives underwater and lands on shallow water tiles, he cannot surface back up. Enemies will also adjust their layering to the shallow water and not the deep one, which means that some enemies are not reachable despite seeming so and the opposite is also true.

- Camera gets slightly broken in the section starting in the room shown in screenshot 9. Link will end up outside of the camera bounds if walking without stopping, but this doesn't break the dungeon. Everything returns to normal once Zora Link gets back in the room in screenshot 9 and goes far enough northwards.

- Arrghus deals 2 HPH, which leads to a threeshot situation. It's aggravated by the tightness of the arena, which makes it nigh-impossible to avoid the Argii-spin attack if the boss has many Argii left. Arrghus' fireballs don't spawn if Link goes behind it.

- The Tears of Time have no icon in the inventory. They currently use the Moon Pearl icon.

**Comment by scawful** [comment]
All the bugs mentioned have been addressed besides the camera in the Zora Temple which I’ll address as apart of #28
