### ISSUE TITLE
GBC Link graphical errors

### ISSUE THREAD

**Issue by scawful** [scawful/Oracle-of-Secrets#20]
GBC Link loses his palette when opening and closing the world map 

GBC Link does not retain his form when entering dungeons from the dark world

**Comment by JaredBrian** [comment]
this one will be hard, I did look into it a little but I couldn't come up with anything that might be causing it and reproducing it is extremely inconsistent.

**Comment by scawful** [comment]
Transforming when using dungeon entrances been solved with a small hook, and the map update shouldn't be too bad since I'm using the Allhallows map override code. Mainly this issue is to try and keep track of all the places we should be hooking to keep Link in GBC form. A few things I can think of off the bat. 

1. Dies and respawns in Dark World
2. Exits a dungeon to the dark world
3. Day and night hourly palette update
4. Map open and close

The ones covered already are 
1. When using magic mirror
2. When entering a dark world dungeon

The code is here [Oracle-of-Secrets/Masks/gbc_form.asm](https://github.com/scawful/Oracle-of-Secrets/blob/master/Masks/gbc_form.asm)
