### ISSUE TITLE
[Menu] Add current time to status screen

### ISSUE THREAD

**Issue by scawful** [scawful/Oracle-of-Secrets#6]

**Comment by JaredBrian** [comment]
Do we have the GFX to do this already? or do we need to make some number with a  black background to accomplish this?

**Comment by scawful** [comment]
We do have GFX for numbers and a colon already. It is at the bottom of the 2bpp graphics space seen below

![image](https://github.com/scawful/Oracle-of-Secrets/assets/47263509/d30096c5-6f7c-4c67-8946-94ab0b1f1436)
