### ISSUE TITLE
Link freezes if going to item menu while shooting with the bow

### ISSUE THREAD

**Issue by 19Linkan90** [scawful/Oracle-of-Secrets#73]
The same problem as there was before with for example the bottle/net
![Screenshot_20240704-090505](https://github.com/scawful/Oracle-of-Secrets/assets/174653314/cfd9e676-468d-49a9-ab51-66be6b595b88)

**Comment by scawful** [comment]
in the latest patch this should be mostly fixed, you will release an arrow after unpausing if the animation is canceled in a frame perfect way but you won't be stuck in the bow animation anymore.
