### ISSUE TITLE
Text from goron mines when you have played the song for princess zora/ruto

### ISSUE THREAD

**Issue by 19Linkan90** [scawful/Oracle-of-Secrets#74]
+ When you have talked to her once you can go right through her, just like you could with the mask seller in a previous patch
![Snapchat-2037001245](https://github.com/scawful/Oracle-of-Secrets/assets/174653314/7fdcb76f-af9a-4240-bfd3-9f35a0b93654)

**Comment by scawful** [comment]
Thank you for bringing this to my attention. I've added the `Sprite_PlayerCantPassThrough` function to make her solid and updated the followup dialogue.
