### ISSUE TITLE
Wrong dungeon highlighted on the map after finished Zora temple

### ISSUE THREAD

**Issue by 19Linkan90** [scawful/Oracle-of-Secrets#75]
((Patch 0.139))
After I finished the Zora temple and check the map, dungeon 4 is still highlighted but not dungeon 5 (Glacia Estate)
![Snapchat-837280775](https://github.com/scawful/Oracle-of-Secrets/assets/174653314/d9d31d4c-249c-431c-bcbc-df36e806d932)

**Comment by scawful** [comment]
I went through and organized the dungeon IDs and fixed the associated save ram with the icons last night, so it will be fixed in the next patch. Thank you.
