### ISSUE TITLE
Link stuck with hands in the air if he lifts something while deku enemy is spinning

### ISSUE THREAD

**Issue by 19Linkan90** [scawful/Oracle-of-Secrets#77]
if link picks up an object while deku is spinning around, the object link is holding disappears and link is stuck in a position with his hands in the air.
(Too big video file, see bug report)

**Comment by scawful** [comment]
This was caused by code to clear the pea shot sprite and the liftable object was subsequently spawned in the same slot, so the scrub dismissed it. This code has been moved to run once when the collision is detected properly.
